### ISSUE TITLE
Se debe refactorizar el código

### ISSUE THREAD

**Issue by evolentini** [cbiale/tp2_iot#1]
Al tener funcionando las pruebas se debe refactorizar el código para hacerlo mas claro y eliminar código duplicado. En tu caso lo mas claro es que el lazo de búsqueda en el arreglo se repite varias veces

https://github.com/cbiale/tp2_iot/blob/bf95baec5444178c3d9fffed94de77b8f893d551/src/lista.js#L31-L34

Lo ideal es definir un método privado que devuelve el indice del elemento buscado y utilizar esa método interno en los métodos públicos de agregar, buscar y borrar.

**Comment by cbiale** [comment]
Se ha agregado el método privado buscarPosicionElemento().
